apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llm
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Caikit Standalone ServingRuntime for KServe
    opendatahub.io/template-name: caikit-standalone-runtime
    openshift.io/display-name: llm
    prometheus.io/path: /metrics
    prometheus.io/port: "8086"
spec:
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: caikit
  containers:
    - name: kserve-container
      # image: quay.io/opendatahub/caikit-nlp:stable-994ec60
      image: quay.io/rh-ee-mmisiura/caikit-nlp:cd44077
      command: ["python", "-m", "caikit.runtime"]
      env:
        - name: RUNTIME_LOCAL_MODELS_DIR
          value: /mnt/models
        - name: HF_HOME
          value: /tmp/hf_home
        - name: RUNTIME_GRPC_ENABLED
          value: "true"
        - name: RUNTIME_HTTP_ENABLED
          value: "false"
      ports:
        - containerPort: 8085
          name: h2c
          protocol: TCP
      livenessProbe:
        exec:
          command: ["python", "-m", "caikit_health_probe", "liveness"]
        initialDelaySeconds: 5
      readinessProbe:
        exec:
          command: ["python", "-m", "caikit_health_probe", "readiness"]
        initialDelaySeconds: 5
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi