# This is the model puller image that serves as the initContainer for the minio pod.
FROM python:3.11-slim

RUN python -m venv /tmp/venv &&\
    /tmp/venv/bin/pip install -U "huggingface_hub[cli]" &&\
    mkdir /.cache &&\
    chmod -R 777 /.cache

ENTRYPOINT ["top", "-b"]