apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llm
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    openshift.io/display-name: llm
    security.opendatahub.io/enable-auth: 'true'
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 20Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '4'
          memory: 18Gi
          nvidia.com/gpu: '1'
      runtime: vllm-runtime-fp16
      storage:
        key: aws-connection-minio-data-connection
        path: Qwen2.5-0.5B-Instruct
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists