apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: regex-detector
  annotations:
    openshift.io/display-name: regex-detector
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    maxReplicas: 1
    minReplicas: 1
    containers:
      - name: kserve-container
        image: quay.io/rh-ee-mmisiura/detector-regex:trial
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 20
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi