#################################### Deployment Spec ####################################
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fms-orchestr8-nlp
  annotations:
    configmap.reloader.stakater.com/reload: 'fms-orchestr8-config'
  labels:
    app: fmstack-nlp
    component: fms-orchestr8-nlp
    deploy-name: fms-orchestr8-nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fmstack-nlp
      component: fms-orchestr8-nlp
      deploy-name: fms-orchestr8-nlp
  template:
    metadata:
      labels:
        app: fmstack-nlp
        component: fms-orchestr8-nlp
        deploy-name: fms-orchestr8-nlp
    spec:
      volumes:
        - name: fms-orchestr8-config-nlp
          configMap:
            name: fms-orchestr8-config-nlp
            defaultMode: 420
        - name: server-tls
          secret:
            secretName: gpt2
            defaultMode: 256
        # - name: ca-cert
        #   secret:
        #     secretName: user-one-token-rwz8b
        #     items:
        #       - key: ca.crt
        #         path: ca.crt
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8033
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: fms-orchestr8-nlp
          command:
            - /app/bin/fms-guardrails-orchestr8
          env:
            - name: ORCHESTRATOR_CONFIG
              value: /config/config.yaml
            - name: HTTPS_PORT
              value: '8033'
            # - name: TLS_KEY_PATH
            #   value: /tls/server/tls.key
            # - name: TLS_CERT_PATH
            #   value: /tls/server/tls.crt
            # - name: TLS_CLIENT_CA_CERT_PATH
            #   value: /tls/ca/ca.crt
            - name: RUST_BACKTRACE
              value: full
            - name: RUST_LOG
              value: 'fms_guardrails_orchestr8=debug'
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: https
              containerPort: 8033
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: fms-orchestr8-config-nlp
              readOnly: true
              mountPath: /config/config.yaml
              subPath: config.yaml
            - name: server-tls
              readOnly: true
              mountPath: /tls/server
            # - name: ca-cert
            #   readOnly: true
            #   mountPath: /tls/ca
          terminationMessagePolicy: File
          image: 'quay.io/rh-ee-mmisiura/fms-orchestr8-nlp:latest'

#################################### Configmap ##########################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fmstack-nlp
    component: fms-orchestr8-nlp
    deploy-name: fms-orchestr8-nlp
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
    generation:
      provider: nlp
      service:
        hostname: gpt2-test.apps.rosa.mac-trustyai.swih.p3.openshiftapps.com
        port: 443
        protocol: grpc
        tls: caikit
    detectors:
      regex:
        service:
          hostname: https://regex-detector-test.apps.rosa.mac-trustyai.swih.p3.openshiftapps.com/api/v1/text/contents
          port: 443
          protocol: https
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
    passthrough_headers: 
      - Authorization
    tls:
      caikit:
        cert_path: /tls/server/tls.crt
        key_path: /tls/server/tls.key
        client_ca_cert_path: /tls/ca/ca.crt
      orchestrator:
        cert_path: /tls/server/tls.crt
        key_path: /tls/server/tls.key
        client_ca_cert_path: /tls/ca/ca.crt

#################################### Service Spec #######################################
---
kind: Service
apiVersion: v1
metadata:
  name: fms-orchestr8-nlp
  labels:
    app: fmstack-nlp
    component: fms-orchestr8-nlp
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: https
      protocol: TCP
      port: 8033
      targetPort: 8033
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: fmstack-nlp
    component: fms-orchestr8-nlp
    deploy-name: fms-orchestr8-nlp

#################################### Route Spec #########################################
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gr2-nlp
  labels:
    app: fmstack-nlp
    component: fms-orchestr8-nlp
spec:
  to:
    kind: Service
    name: fms-orchestr8-nlp
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None